from __future__ import annotations

from pathlib import Path
from datetime import date
from typing import Protocol

from sqlalchemy import Table
from sqlalchemy.engine import Engine

from ..types import (
    BootstrapPayloadData,
    CatalogOfferingData,
    CatalogProductData,
    CustomerProfileData,
    InvoiceDetailData,
    InvoiceFileData,
    InvoiceListItemData,
    PriceListMetaData,
    TransportData,
)


class PostgresRepositoryProtocol(Protocol):
    base_dir: Path
    url: str
    engine: Engine
    catalogs: Table
    price_lists: Table
    transports: Table
    customers: Table
    products: Table
    product_offerings: Table
    invoice_batches: Table
    invoices: Table
    invoice_items: Table
    invoice_tax_breakdown: Table
    arca_requests: Table
    invoice_sequences: Table
    app_users: Table

    def _resolve_transport_id(self, *, connection, transport_name: str | None, now) -> int | None: ...
    def _ensure_offering_net_weight(self, *, connection) -> None: ...
    def _ensure_invoice_historical_snapshot_fields(self, *, connection) -> None: ...
    def _sync_customer_references(self, *, connection, now) -> None: ...
    def _sync_catalog_tables(self, catalog: list[CatalogProductData], *, connection, now) -> None: ...
    def _refresh_active_catalog_snapshot(self, *, connection, now) -> None: ...
    def _catalog_snapshot(self, *, connection, active_only: bool = True) -> list[CatalogProductData]: ...
    def _upsert_customer(self, customer: CustomerProfileData | dict[str, object], *, connection, now) -> int: ...
    def get_profiles_map(self) -> dict[str, CustomerProfileData]: ...
    def get_active_catalog(self) -> list[CatalogProductData]: ...
    def get_catalog_for_price_list(self, price_list_id: int) -> list[CatalogProductData]: ...
    def delete_price_list(self, price_list_id: int) -> None: ...
    def rename_price_list(self, price_list_id: int, name: str) -> None: ...
    def get_transports(self) -> list[TransportData]: ...
    def list_price_lists(self) -> list[PriceListMetaData]: ...
    def get_active_price_list_meta(self) -> PriceListMetaData | None: ...
    def list_invoices(self, limit: int = 50, date_from: date | None = None) -> list[InvoiceListItemData]: ...
    def get_invoice_detail(self, invoice_id: int) -> InvoiceDetailData | None: ...
    def get_invoice_file(self, invoice_id: int) -> InvoiceFileData | None: ...
    def save_invoice_batch(self, *, batch: dict[str, object], invoices: list[dict[str, object]], update_customer: bool = True, replace_batch_id: int | None = None) -> tuple[int, list[int]]: ...
    def list_batch_invoice_statuses(self, batch_id: int) -> list[dict[str, object]]: ...
    def get_invoice_tax_breakdown(self, invoice_id: int) -> list[dict[str, object]]: ...
    def reserve_invoice_arca_authorization(self, invoice_id: int) -> bool: ...
    def release_invoice_arca_authorization(self, invoice_id: int, fiscal_status: str = "draft") -> None: ...
    def create_arca_request(self, *, invoice_id: int, operation: str, environment: str, sanitized_request: dict[str, object], status: str = "pending", sanitized_response: dict[str, object] | None = None, error_code: str | None = None, error_message: str | None = None) -> int: ...
    def update_arca_request(self, arca_request_id: int, *, status: str, sanitized_response: dict[str, object] | None = None, error_code: str | None = None, error_message: str | None = None) -> None: ...
    def update_invoice_arca_status(self, invoice_id: int, *, fiscal_status: str, arca_environment: str, arca_cuit_emisor: str, arca_cbte_tipo: int, arca_concepto: int, arca_doc_tipo: int, arca_doc_nro: str, arca_point_of_sale: int, arca_request_id: int, arca_invoice_number: int | None = None, arca_cae: str | None = None, arca_cae_expires_at: object | None = None, arca_result: str | None = None, arca_observations: object | None = None, arca_error_code: str | None = None, arca_error_message: str | None = None) -> None: ...
    def save_product(self, payload: CatalogProductData) -> CatalogProductData: ...
    def save_product_offerings(self, product_id: int, offerings: list[CatalogOfferingData]) -> None: ...
    def update_price_list_product(self, price_list_id: int, product: CatalogProductData, offerings: list[CatalogOfferingData]) -> CatalogProductData: ...
    def save_transport(self, name: str, notes: list[str] | None = None, transport_id: int | None = None) -> TransportData: ...
    def save_price_list(self, filename: str, pdf_bytes: bytes, activate: bool = True, source: str = "upload", name: str | None = None, price_list_id: int | None = None) -> PriceListMetaData: ...
    def save_price_list_with_catalog(self, *, filename: str, pdf_bytes: bytes, catalog: list[CatalogProductData], activate: bool = True, source: str = "upload", name: str | None = None, price_list_id: int | None = None) -> PriceListMetaData: ...
    def bootstrap_payload(self) -> BootstrapPayloadData: ...
