from __future__ import annotations

from sqlalchemy import BigInteger, Boolean, CheckConstraint, Column, Date, DateTime, ForeignKey, Integer, LargeBinary, MetaData, String, Table, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB


def build_metadata() -> tuple[MetaData, dict[str, Table]]:
    metadata = MetaData()
    tables = {
        "catalogs": Table(
            "catalogs",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("name", String(255), nullable=False),
            Column("active", Boolean, nullable=False, server_default="false"),
            Column("source", String(120), nullable=False),
            Column("catalog", JSONB, nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(name)) > 0", name="ck_catalogs_name_not_blank"),
            CheckConstraint("char_length(btrim(source)) > 0", name="ck_catalogs_source_not_blank"),
            CheckConstraint("jsonb_typeof(catalog) = 'array'", name="ck_catalogs_catalog_array"),
        ),
        "price_lists": Table(
            "price_lists",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("filename", String(255), nullable=False),
            Column("content_type", String(120), nullable=False),
            Column("size", Integer, nullable=False),
            Column("pdf_data", LargeBinary, nullable=False),
            Column("active", Boolean, nullable=False, server_default="false"),
            Column("source", String(120), nullable=False),
            Column("uploaded_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(filename)) > 0", name="ck_price_lists_filename_not_blank"),
            CheckConstraint("char_length(btrim(content_type)) > 0", name="ck_price_lists_content_type_not_blank"),
            CheckConstraint("char_length(btrim(source)) > 0", name="ck_price_lists_source_not_blank"),
            CheckConstraint("size > 0 AND size <= 20971520", name="ck_price_lists_size_range"),
            CheckConstraint("octet_length(pdf_data) = size", name="ck_price_lists_pdf_size_matches"),
        ),
        "transports": Table(
            "transports",
            metadata,
            Column("transport_id", BigInteger, primary_key=True, autoincrement=True),
            Column("name", String(255), nullable=False, unique=True),
            Column("notes", JSONB, nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(name)) > 0", name="ck_transports_name_not_blank"),
            CheckConstraint("jsonb_typeof(notes) = 'array'", name="ck_transports_notes_array"),
            CheckConstraint("CASE WHEN jsonb_typeof(notes) = 'array' THEN jsonb_array_length(notes) <= 30 ELSE false END", name="ck_transports_notes_max_items"),
        ),
        "customers": Table(
            "customers",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("name", String(255), nullable=False),
            Column("secondary_line", Text, nullable=False, server_default=""),
            Column("notes", JSONB, nullable=False),
            Column("footer_discounts", JSONB, nullable=False),
            Column("line_discounts_by_format", JSONB, nullable=False),
            Column("source_count", Integer, nullable=False, server_default="0"),
            Column("transport_id", BigInteger, ForeignKey("transports.transport_id", ondelete="SET NULL")),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(name)) > 0", name="ck_customers_name_not_blank"),
            CheckConstraint("char_length(secondary_line) <= 500", name="ck_customers_secondary_line_max_length"),
            CheckConstraint("jsonb_typeof(notes) = 'array'", name="ck_customers_notes_array"),
            CheckConstraint("CASE WHEN jsonb_typeof(notes) = 'array' THEN jsonb_array_length(notes) <= 30 ELSE false END", name="ck_customers_notes_max_items"),
            CheckConstraint("jsonb_typeof(footer_discounts) = 'array'", name="ck_customers_footer_discounts_array"),
            CheckConstraint("CASE WHEN jsonb_typeof(footer_discounts) = 'array' THEN jsonb_array_length(footer_discounts) <= 30 ELSE false END", name="ck_customers_footer_discounts_max_items"),
            CheckConstraint("jsonb_typeof(line_discounts_by_format) = 'object'", name="ck_customers_line_discounts_object"),
            CheckConstraint("source_count >= 0", name="ck_customers_source_count_nonnegative"),
        ),
        "products": Table(
            "products",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("name", String(255), nullable=False),
            Column("aliases", JSONB, nullable=False),
            Column("active", Boolean, nullable=False, server_default="true"),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(name)) > 0", name="ck_products_name_not_blank"),
            CheckConstraint("jsonb_typeof(aliases) = 'array'", name="ck_products_aliases_array"),
            CheckConstraint("CASE WHEN jsonb_typeof(aliases) = 'array' THEN jsonb_array_length(aliases) <= 50 ELSE false END", name="ck_products_aliases_max_items"),
        ),
        "product_offerings": Table(
            "product_offerings",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("product_id", BigInteger, ForeignKey("products.id", ondelete="CASCADE"), nullable=False),
            Column("label", String(120), nullable=False),
            Column("price", Integer, nullable=False),
            Column("position", Integer, nullable=False),
            Column("active", Boolean, nullable=False, server_default="true"),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(label)) > 0", name="ck_product_offerings_label_not_blank"),
            CheckConstraint("price >= 0", name="ck_product_offerings_price_nonnegative"),
            CheckConstraint("position > 0", name="ck_product_offerings_position_positive"),
            UniqueConstraint("product_id", "label"),
        ),
        "invoices": Table(
            "invoices",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("customer_id", BigInteger, ForeignKey("customers.id", ondelete="SET NULL")),
            Column("transport_id", BigInteger, ForeignKey("transports.transport_id", ondelete="SET NULL")),
            Column("legacy_key", String(255), unique=True),
            Column("client_name", String(255), nullable=False),
            Column("order_date", Date, nullable=False),
            Column("secondary_line", Text, nullable=False, server_default=""),
            Column("transport", Text, nullable=False, server_default=""),
            Column("notes", JSONB, nullable=False),
            Column("footer_discounts", JSONB, nullable=False),
            Column("line_discounts_by_format", JSONB, nullable=False),
            Column("total_bultos", Integer, nullable=False),
            Column("gross_total", Integer, nullable=False),
            Column("discount_total", Integer, nullable=False),
            Column("final_total", Integer, nullable=False),
            Column("output_filename", String(255), nullable=False),
            Column("xlsx_data", LargeBinary, nullable=False),
            Column("xlsx_size", Integer, nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("legacy_key IS NULL OR char_length(btrim(legacy_key)) > 0", name="ck_invoices_legacy_key_not_blank"),
            CheckConstraint("char_length(btrim(client_name)) > 0", name="ck_invoices_client_name_not_blank"),
            CheckConstraint("char_length(secondary_line) <= 500", name="ck_invoices_secondary_line_max_length"),
            CheckConstraint("char_length(transport) <= 500", name="ck_invoices_transport_max_length"),
            CheckConstraint("jsonb_typeof(notes) = 'array'", name="ck_invoices_notes_array"),
            CheckConstraint("CASE WHEN jsonb_typeof(notes) = 'array' THEN jsonb_array_length(notes) <= 30 ELSE false END", name="ck_invoices_notes_max_items"),
            CheckConstraint("jsonb_typeof(footer_discounts) = 'array'", name="ck_invoices_footer_discounts_array"),
            CheckConstraint("CASE WHEN jsonb_typeof(footer_discounts) = 'array' THEN jsonb_array_length(footer_discounts) <= 30 ELSE false END", name="ck_invoices_footer_discounts_max_items"),
            CheckConstraint("jsonb_typeof(line_discounts_by_format) = 'object'", name="ck_invoices_line_discounts_object"),
            CheckConstraint("total_bultos >= 0", name="ck_invoices_total_bultos_nonnegative"),
            CheckConstraint("gross_total >= 0", name="ck_invoices_gross_total_nonnegative"),
            CheckConstraint("discount_total >= 0", name="ck_invoices_discount_total_nonnegative"),
            CheckConstraint("final_total >= 0", name="ck_invoices_final_total_nonnegative"),
            CheckConstraint("discount_total <= gross_total", name="ck_invoices_discount_not_above_gross"),
            CheckConstraint("char_length(btrim(output_filename)) > 0", name="ck_invoices_output_filename_not_blank"),
            CheckConstraint("xlsx_size > 0", name="ck_invoices_xlsx_size_positive"),
            CheckConstraint("octet_length(xlsx_data) = xlsx_size", name="ck_invoices_xlsx_size_matches"),
        ),
        "invoice_items": Table(
            "invoice_items",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("invoice_id", BigInteger, ForeignKey("invoices.id", ondelete="CASCADE"), nullable=False),
            Column("line_number", Integer, nullable=False),
            Column("product_id", BigInteger, ForeignKey("products.id", ondelete="SET NULL")),
            Column("offering_id", BigInteger, ForeignKey("product_offerings.id", ondelete="SET NULL")),
            Column("label", Text, nullable=False),
            Column("quantity", Integer, nullable=False),
            Column("unit_price", Integer, nullable=False),
            Column("gross", Integer, nullable=False),
            Column("discount", Integer, nullable=False),
            Column("total", Integer, nullable=False),
            CheckConstraint("line_number > 0", name="ck_invoice_items_line_number_positive"),
            CheckConstraint("char_length(btrim(label)) > 0", name="ck_invoice_items_label_not_blank"),
            CheckConstraint("quantity >= 0", name="ck_invoice_items_quantity_nonnegative"),
            CheckConstraint("unit_price >= 0", name="ck_invoice_items_unit_price_nonnegative"),
            CheckConstraint("gross >= 0", name="ck_invoice_items_gross_nonnegative"),
            CheckConstraint("discount >= 0", name="ck_invoice_items_discount_nonnegative"),
            CheckConstraint("total >= 0", name="ck_invoice_items_total_nonnegative"),
            CheckConstraint("discount <= gross", name="ck_invoice_items_discount_not_above_gross"),
        ),
        "app_users": Table(
            "app_users",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("username", String(120), nullable=False, unique=True),
            Column("password_hash", String(255), nullable=False),
            Column("is_active", Boolean, nullable=False, server_default="true"),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(username)) > 0", name="ck_app_users_username_not_blank"),
            CheckConstraint("char_length(btrim(password_hash)) > 0", name="ck_app_users_password_hash_not_blank"),
        ),
    }
    return metadata, tables
