from __future__ import annotations

from sqlalchemy import BigInteger, Boolean, Column, Date, DateTime, ForeignKey, Integer, LargeBinary, MetaData, String, Table, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB


def build_metadata() -> tuple[MetaData, dict[str, Table]]:
    metadata = MetaData()
    tables = {
        "catalogs": Table(
            "catalogs",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("name", String(255), nullable=False),
            Column("active", Boolean, nullable=False, server_default="false"),
            Column("source", String(120), nullable=False),
            Column("catalog", JSONB, nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
        ),
        "price_lists": Table(
            "price_lists",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("filename", String(255), nullable=False),
            Column("content_type", String(120), nullable=False),
            Column("size", Integer, nullable=False),
            Column("pdf_data", LargeBinary, nullable=False),
            Column("active", Boolean, nullable=False, server_default="false"),
            Column("source", String(120), nullable=False),
            Column("uploaded_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
        ),
        "transports": Table(
            "transports",
            metadata,
            Column("transport_id", BigInteger, primary_key=True, autoincrement=True),
            Column("name", String(255), nullable=False, unique=True),
            Column("notes", JSONB, nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
        ),
        "customers": Table(
            "customers",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("name", String(255), nullable=False),
            Column("secondary_line", Text, nullable=False, server_default=""),
            Column("notes", JSONB, nullable=False),
            Column("footer_discounts", JSONB, nullable=False),
            Column("line_discounts_by_format", JSONB, nullable=False),
            Column("source_count", Integer, nullable=False, server_default="0"),
            Column("transport_id", BigInteger, ForeignKey("transports.transport_id", ondelete="SET NULL")),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
        ),
        "products": Table(
            "products",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("name", String(255), nullable=False),
            Column("aliases", JSONB, nullable=False),
            Column("active", Boolean, nullable=False, server_default="true"),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
        ),
        "product_offerings": Table(
            "product_offerings",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("product_id", BigInteger, ForeignKey("products.id", ondelete="CASCADE"), nullable=False),
            Column("label", String(120), nullable=False),
            Column("price", Integer, nullable=False),
            Column("position", Integer, nullable=False),
            Column("active", Boolean, nullable=False, server_default="true"),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            UniqueConstraint("product_id", "label"),
        ),
        "invoices": Table(
            "invoices",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("customer_id", BigInteger, ForeignKey("customers.id", ondelete="SET NULL")),
            Column("transport_id", BigInteger, ForeignKey("transports.transport_id", ondelete="SET NULL")),
            Column("legacy_key", String(255), unique=True),
            Column("client_name", String(255), nullable=False),
            Column("order_date", Date, nullable=False),
            Column("secondary_line", Text, nullable=False, server_default=""),
            Column("transport", Text, nullable=False, server_default=""),
            Column("notes", JSONB, nullable=False),
            Column("footer_discounts", JSONB, nullable=False),
            Column("line_discounts_by_format", JSONB, nullable=False),
            Column("total_bultos", Integer, nullable=False),
            Column("gross_total", Integer, nullable=False),
            Column("discount_total", Integer, nullable=False),
            Column("final_total", Integer, nullable=False),
            Column("output_filename", String(255), nullable=False),
            Column("xlsx_data", LargeBinary, nullable=False),
            Column("xlsx_size", Integer, nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
        ),
        "invoice_items": Table(
            "invoice_items",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("invoice_id", BigInteger, ForeignKey("invoices.id", ondelete="CASCADE"), nullable=False),
            Column("line_number", Integer, nullable=False),
            Column("product_id", BigInteger, ForeignKey("products.id", ondelete="SET NULL")),
            Column("offering_id", BigInteger, ForeignKey("product_offerings.id", ondelete="SET NULL")),
            Column("label", Text, nullable=False),
            Column("quantity", Integer, nullable=False),
            Column("unit_price", Integer, nullable=False),
            Column("gross", Integer, nullable=False),
            Column("discount", Integer, nullable=False),
            Column("total", Integer, nullable=False),
        ),
        "app_users": Table(
            "app_users",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("username", String(120), nullable=False, unique=True),
            Column("password_hash", String(255), nullable=False),
            Column("is_active", Boolean, nullable=False, server_default="true"),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
        ),
    }
    return metadata, tables
