from __future__ import annotations

from sqlalchemy import BigInteger, Boolean, CheckConstraint, Column, Date, DateTime, ForeignKey, Integer, LargeBinary, MetaData, Numeric, String, Table, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import JSONB


def build_metadata() -> tuple[MetaData, dict[str, Table]]:
    metadata = MetaData()
    tables = {
        "catalogs": Table(
            "catalogs",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("price_list_id", BigInteger, ForeignKey("price_lists.id", ondelete="SET NULL")),
            Column("name", String(255), nullable=False),
            Column("active", Boolean, nullable=False, server_default="false"),
            Column("source", String(120), nullable=False),
            Column("catalog", JSONB, nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(name)) > 0", name="ck_catalogs_name_not_blank"),
            CheckConstraint("char_length(btrim(source)) > 0", name="ck_catalogs_source_not_blank"),
            CheckConstraint("jsonb_typeof(catalog) = 'array'", name="ck_catalogs_catalog_array"),
        ),
        "price_lists": Table(
            "price_lists",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("name", String(255), nullable=False, server_default="Lista principal"),
            Column("filename", String(255), nullable=False),
            Column("content_type", String(120), nullable=False),
            Column("size", Integer, nullable=False),
            Column("pdf_data", LargeBinary, nullable=False),
            Column("active", Boolean, nullable=False, server_default="false"),
            Column("source", String(120), nullable=False),
            Column("uploaded_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(name)) > 0", name="ck_price_lists_name_not_blank"),
            CheckConstraint("char_length(btrim(filename)) > 0", name="ck_price_lists_filename_not_blank"),
            CheckConstraint("char_length(btrim(content_type)) > 0", name="ck_price_lists_content_type_not_blank"),
            CheckConstraint("char_length(btrim(source)) > 0", name="ck_price_lists_source_not_blank"),
            CheckConstraint("size > 0 AND size <= 20971520", name="ck_price_lists_size_range"),
            CheckConstraint("octet_length(pdf_data) = size", name="ck_price_lists_pdf_size_matches"),
        ),
        "transports": Table(
            "transports",
            metadata,
            Column("transport_id", BigInteger, primary_key=True, autoincrement=True),
            Column("name", String(255), nullable=False, unique=True),
            Column("notes", JSONB, nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(name)) > 0", name="ck_transports_name_not_blank"),
            CheckConstraint("jsonb_typeof(notes) = 'array'", name="ck_transports_notes_array"),
            CheckConstraint("CASE WHEN jsonb_typeof(notes) = 'array' THEN jsonb_array_length(notes) <= 30 ELSE false END", name="ck_transports_notes_max_items"),
        ),
        "customers": Table(
            "customers",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("name", String(255), nullable=False),
            Column("cuit", String(32), nullable=False, server_default=""),
            Column("address", Text, nullable=False, server_default=""),
            Column("business_name", String(255), nullable=False, server_default=""),
            Column("email", String(255), nullable=False, server_default=""),
            Column("secondary_line", Text, nullable=False, server_default=""),
            Column("notes", JSONB, nullable=False),
            Column("footer_discounts", JSONB, nullable=False),
            Column("line_discounts_by_format", JSONB, nullable=False),
            Column("automatic_bonus_rules", JSONB, nullable=False, server_default="[]"),
            Column("automatic_bonus_disables_line_discount", Boolean, nullable=False, server_default="false"),
            Column("source_count", Integer, nullable=False, server_default="0"),
            Column("transport_id", BigInteger, ForeignKey("transports.transport_id", ondelete="SET NULL")),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(name)) > 0", name="ck_customers_name_not_blank"),
            CheckConstraint("char_length(cuit) <= 32", name="ck_customers_cuit_max_length"),
            CheckConstraint("char_length(address) <= 500", name="ck_customers_address_max_length"),
            CheckConstraint("char_length(business_name) <= 255", name="ck_customers_business_name_max_length"),
            CheckConstraint("char_length(email) <= 255", name="ck_customers_email_max_length"),
            CheckConstraint("char_length(secondary_line) <= 500", name="ck_customers_secondary_line_max_length"),
            CheckConstraint("jsonb_typeof(notes) = 'array'", name="ck_customers_notes_array"),
            CheckConstraint("CASE WHEN jsonb_typeof(notes) = 'array' THEN jsonb_array_length(notes) <= 30 ELSE false END", name="ck_customers_notes_max_items"),
            CheckConstraint("jsonb_typeof(footer_discounts) = 'array'", name="ck_customers_footer_discounts_array"),
            CheckConstraint("CASE WHEN jsonb_typeof(footer_discounts) = 'array' THEN jsonb_array_length(footer_discounts) <= 30 ELSE false END", name="ck_customers_footer_discounts_max_items"),
            CheckConstraint("jsonb_typeof(line_discounts_by_format) = 'object'", name="ck_customers_line_discounts_object"),
            CheckConstraint("jsonb_typeof(automatic_bonus_rules) = 'array'", name="ck_customers_automatic_bonus_rules_array"),
            CheckConstraint("CASE WHEN jsonb_typeof(automatic_bonus_rules) = 'array' THEN jsonb_array_length(automatic_bonus_rules) <= 100 ELSE false END", name="ck_customers_automatic_bonus_rules_max_items"),
            CheckConstraint("source_count >= 0", name="ck_customers_source_count_nonnegative"),
        ),
        "products": Table(
            "products",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("name", String(255), nullable=False),
            Column("aliases", JSONB, nullable=False),
            Column("active", Boolean, nullable=False, server_default="true"),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(name)) > 0", name="ck_products_name_not_blank"),
            CheckConstraint("jsonb_typeof(aliases) = 'array'", name="ck_products_aliases_array"),
            CheckConstraint("CASE WHEN jsonb_typeof(aliases) = 'array' THEN jsonb_array_length(aliases) <= 50 ELSE false END", name="ck_products_aliases_max_items"),
        ),
        "product_offerings": Table(
            "product_offerings",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("product_id", BigInteger, ForeignKey("products.id", ondelete="CASCADE"), nullable=False),
            Column("label", String(120), nullable=False),
            Column("price", Integer, nullable=False),
            Column("net_weight_kg", Numeric(12, 3), nullable=False, server_default="0"),
            Column("iva_rate_id", Integer, ForeignKey("arca_iva_rates.arca_id", ondelete="SET NULL")),
            Column("iva_rate_percent", Numeric(6, 3)),
            Column("position", Integer, nullable=False),
            Column("active", Boolean, nullable=False, server_default="true"),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(label)) > 0", name="ck_product_offerings_label_not_blank"),
            CheckConstraint("price >= 0", name="ck_product_offerings_price_nonnegative"),
            CheckConstraint("net_weight_kg >= 0", name="ck_product_offerings_net_weight_nonnegative"),
            CheckConstraint("iva_rate_percent IS NULL OR iva_rate_percent >= 0", name="ck_product_offerings_iva_rate_percent_nonnegative"),
            CheckConstraint("position > 0", name="ck_product_offerings_position_positive"),
            UniqueConstraint("product_id", "label"),
        ),
        "invoices": Table(
            "invoices",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("customer_id", BigInteger, ForeignKey("customers.id", ondelete="SET NULL")),
            Column("transport_id", BigInteger, ForeignKey("transports.transport_id", ondelete="SET NULL")),
            Column("price_list_id", BigInteger, ForeignKey("price_lists.id", ondelete="SET NULL")),
            Column("legacy_key", String(255), unique=True),
            Column("document_type", String(30), nullable=False, server_default="FACTURA"),
            Column("point_of_sale", Integer, nullable=False, server_default="1"),
            Column("invoice_number", BigInteger, nullable=False),
            Column("internal_number", BigInteger, nullable=False),
            Column("fiscal_kind", String(20), nullable=False, server_default="internal"),
            Column("fiscal_status", String(30), nullable=False, server_default="draft"),
            Column("client_name", String(255), nullable=False),
            Column("declared", Boolean, nullable=False, server_default="false"),
            Column("arca_environment", String(20)),
            Column("arca_cbte_tipo", Integer),
            Column("arca_point_of_sale", Integer),
            Column("arca_invoice_number", BigInteger),
            Column("arca_cae", String(32)),
            Column("arca_cae_due_date", Date),
            Column("arca_authorized_at", DateTime(timezone=True)),
            Column("arca_result", String(20)),
            Column("arca_observations_json", JSONB),
            Column("arca_errors_json", JSONB),
            Column("arca_request_id", BigInteger, ForeignKey("arca_requests.id", ondelete="SET NULL")),
            Column("locked_at", DateTime(timezone=True)),
            Column("locked_by", String(120)),
            Column("price_list_name", String(255), nullable=False, server_default=""),
            Column("price_list_effective_date", DateTime(timezone=True)),
            Column("customer_cuit", String(32)),
            Column("customer_address", Text),
            Column("customer_business_name", String(255)),
            Column("customer_email", String(255)),
            Column("order_date", Date, nullable=False),
            Column("secondary_line", Text, nullable=False, server_default=""),
            Column("transport", Text, nullable=False, server_default=""),
            Column("notes", JSONB, nullable=False),
            Column("footer_discounts", JSONB, nullable=False),
            Column("line_discounts_by_format", JSONB, nullable=False),
            Column("total_bultos", Numeric(12, 2), nullable=False),
            Column("gross_total", Integer, nullable=False),
            Column("discount_total", Integer, nullable=False),
            Column("final_total", Integer, nullable=False),
            Column("output_filename", String(255), nullable=False),
            Column("xlsx_data", LargeBinary, nullable=False),
            Column("xlsx_size", Integer, nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("legacy_key IS NULL OR char_length(btrim(legacy_key)) > 0", name="ck_invoices_legacy_key_not_blank"),
            CheckConstraint("char_length(btrim(document_type)) > 0", name="ck_invoices_document_type_not_blank"),
            CheckConstraint("point_of_sale > 0", name="ck_invoices_point_of_sale_positive"),
            CheckConstraint("invoice_number > 0", name="ck_invoices_invoice_number_positive"),
            CheckConstraint("internal_number > 0", name="ck_invoices_internal_number_positive"),
            CheckConstraint("fiscal_kind IN ('internal', 'fiscal')", name="ck_invoices_fiscal_kind_valid"),
            CheckConstraint("fiscal_status IN ('draft', 'pending_authorization', 'authorized', 'rejected', 'cancelled')", name="ck_invoices_fiscal_status_valid"),
            CheckConstraint("arca_environment IS NULL OR arca_environment IN ('homologation', 'production')", name="ck_invoices_arca_environment_valid"),
            CheckConstraint("arca_cbte_tipo IS NULL OR arca_cbte_tipo > 0", name="ck_invoices_arca_cbte_tipo_positive"),
            CheckConstraint("arca_point_of_sale IS NULL OR arca_point_of_sale > 0", name="ck_invoices_arca_point_of_sale_positive"),
            CheckConstraint("arca_invoice_number IS NULL OR arca_invoice_number > 0", name="ck_invoices_arca_invoice_number_positive"),
            CheckConstraint("char_length(btrim(client_name)) > 0", name="ck_invoices_client_name_not_blank"),
            CheckConstraint("char_length(customer_cuit) <= 32", name="ck_invoices_customer_cuit_max_length"),
            CheckConstraint("char_length(customer_address) <= 500", name="ck_invoices_customer_address_max_length"),
            CheckConstraint("char_length(customer_business_name) <= 255", name="ck_invoices_customer_business_name_max_length"),
            CheckConstraint("char_length(customer_email) <= 255", name="ck_invoices_customer_email_max_length"),
            CheckConstraint("char_length(secondary_line) <= 500", name="ck_invoices_secondary_line_max_length"),
            CheckConstraint("char_length(transport) <= 500", name="ck_invoices_transport_max_length"),
            CheckConstraint("jsonb_typeof(notes) = 'array'", name="ck_invoices_notes_array"),
            CheckConstraint("CASE WHEN jsonb_typeof(notes) = 'array' THEN jsonb_array_length(notes) <= 30 ELSE false END", name="ck_invoices_notes_max_items"),
            CheckConstraint("jsonb_typeof(footer_discounts) = 'array'", name="ck_invoices_footer_discounts_array"),
            CheckConstraint("CASE WHEN jsonb_typeof(footer_discounts) = 'array' THEN jsonb_array_length(footer_discounts) <= 30 ELSE false END", name="ck_invoices_footer_discounts_max_items"),
            CheckConstraint("jsonb_typeof(line_discounts_by_format) = 'object'", name="ck_invoices_line_discounts_object"),
            CheckConstraint("total_bultos >= 0", name="ck_invoices_total_bultos_nonnegative"),
            CheckConstraint("gross_total >= 0", name="ck_invoices_gross_total_nonnegative"),
            CheckConstraint("discount_total >= 0", name="ck_invoices_discount_total_nonnegative"),
            CheckConstraint("final_total >= 0", name="ck_invoices_final_total_nonnegative"),
            CheckConstraint("discount_total <= gross_total", name="ck_invoices_discount_not_above_gross"),
            CheckConstraint("char_length(btrim(output_filename)) > 0", name="ck_invoices_output_filename_not_blank"),
            CheckConstraint("xlsx_size > 0", name="ck_invoices_xlsx_size_positive"),
            CheckConstraint("octet_length(xlsx_data) = xlsx_size", name="ck_invoices_xlsx_size_matches"),
            UniqueConstraint("document_type", "point_of_sale", "invoice_number", name="uq_invoices_fiscal_number"),
            UniqueConstraint("internal_number", name="uq_invoices_internal_number"),
            UniqueConstraint("arca_environment", "arca_cbte_tipo", "arca_point_of_sale", "arca_invoice_number", name="uq_invoices_arca_number"),
        ),
        "invoice_sequences": Table(
            "invoice_sequences",
            metadata,
            Column("document_type", String(30), nullable=False),
            Column("point_of_sale", Integer, nullable=False),
            Column("next_number", BigInteger, nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(document_type)) > 0", name="ck_invoice_sequences_document_type_not_blank"),
            CheckConstraint("point_of_sale > 0", name="ck_invoice_sequences_point_of_sale_positive"),
            CheckConstraint("next_number > 0", name="ck_invoice_sequences_next_number_positive"),
            UniqueConstraint("document_type", "point_of_sale", name="uq_invoice_sequences_scope"),
        ),
        "arca_iva_rates": Table(
            "arca_iva_rates",
            metadata,
            Column("arca_id", Integer, primary_key=True, nullable=False),
            Column("description", String(120), nullable=False),
            Column("percent", Numeric(6, 3), nullable=False),
            Column("active", Boolean, nullable=False, server_default="true"),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("arca_id > 0", name="ck_arca_iva_rates_arca_id_positive"),
            CheckConstraint("char_length(btrim(description)) > 0", name="ck_arca_iva_rates_description_not_blank"),
            CheckConstraint("percent >= 0", name="ck_arca_iva_rates_percent_nonnegative"),
        ),
        "invoice_tax_breakdown": Table(
            "invoice_tax_breakdown",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("invoice_id", BigInteger, ForeignKey("invoices.id", ondelete="CASCADE"), nullable=False),
            Column("arca_iva_id", Integer, ForeignKey("arca_iva_rates.arca_id", ondelete="RESTRICT"), nullable=False),
            Column("iva_rate_percent", Numeric(6, 3), nullable=False),
            Column("base_amount", Numeric(14, 2), nullable=False),
            Column("tax_amount", Numeric(14, 2), nullable=False),
            Column("created_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("iva_rate_percent >= 0", name="ck_invoice_tax_breakdown_iva_rate_percent_nonnegative"),
            CheckConstraint("base_amount >= 0", name="ck_invoice_tax_breakdown_base_amount_nonnegative"),
            CheckConstraint("tax_amount >= 0", name="ck_invoice_tax_breakdown_tax_amount_nonnegative"),
            UniqueConstraint("invoice_id", "arca_iva_id", name="uq_invoice_tax_breakdown_invoice_rate"),
        ),
        "arca_requests": Table(
            "arca_requests",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("invoice_id", BigInteger, ForeignKey("invoices.id", ondelete="SET NULL")),
            Column("operation", String(60), nullable=False),
            Column("environment", String(20), nullable=False),
            Column("request_xml", Text),
            Column("response_xml", Text),
            Column("parsed_response_json", JSONB),
            Column("status", String(30), nullable=False),
            Column("error_code", String(60)),
            Column("created_by", String(120)),
            Column("created_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(operation)) > 0", name="ck_arca_requests_operation_not_blank"),
            CheckConstraint("environment IN ('homologation', 'production')", name="ck_arca_requests_environment_valid"),
            CheckConstraint("char_length(btrim(status)) > 0", name="ck_arca_requests_status_not_blank"),
        ),
        "invoice_items": Table(
            "invoice_items",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("invoice_id", BigInteger, ForeignKey("invoices.id", ondelete="CASCADE"), nullable=False),
            Column("line_number", Integer, nullable=False),
            Column("product_id", BigInteger, ForeignKey("products.id", ondelete="SET NULL")),
            Column("offering_id", BigInteger, ForeignKey("product_offerings.id", ondelete="SET NULL")),
            Column("product_name", String(255)),
            Column("offering_label", String(120)),
            Column("offering_net_weight_kg", Numeric(12, 3)),
            Column("line_type", String(20), nullable=False, server_default="sale"),
            Column("discount_rate", Numeric(8, 6)),
            Column("label", Text, nullable=False),
            Column("quantity", Numeric(12, 2), nullable=False),
            Column("unit_price", Integer, nullable=False),
            Column("iva_rate_id", Integer, ForeignKey("arca_iva_rates.arca_id", ondelete="SET NULL")),
            Column("iva_rate_percent", Numeric(6, 3)),
            Column("net_unit_price", Numeric(14, 4)),
            Column("gross_unit_price", Numeric(14, 4)),
            Column("tax_amount", Numeric(14, 2)),
            Column("line_net_amount", Numeric(14, 2)),
            Column("line_tax_amount", Numeric(14, 2)),
            Column("line_total_amount", Numeric(14, 2)),
            Column("gross", Integer, nullable=False),
            Column("discount", Integer, nullable=False),
            Column("total", Integer, nullable=False),
            CheckConstraint("line_number > 0", name="ck_invoice_items_line_number_positive"),
            CheckConstraint("char_length(product_name) <= 255", name="ck_invoice_items_product_name_max_length"),
            CheckConstraint("char_length(offering_label) <= 120", name="ck_invoice_items_offering_label_max_length"),
            CheckConstraint("offering_net_weight_kg >= 0", name="ck_invoice_items_offering_net_weight_nonnegative"),
            CheckConstraint("line_type IN ('sale', 'bonus')", name="ck_invoice_items_line_type_valid"),
            CheckConstraint("discount_rate >= 0 AND discount_rate <= 1", name="ck_invoice_items_discount_rate_range"),
            CheckConstraint("char_length(btrim(label)) > 0", name="ck_invoice_items_label_not_blank"),
            CheckConstraint("quantity >= 0", name="ck_invoice_items_quantity_nonnegative"),
            CheckConstraint("unit_price >= 0", name="ck_invoice_items_unit_price_nonnegative"),
            CheckConstraint("iva_rate_percent IS NULL OR iva_rate_percent >= 0", name="ck_invoice_items_iva_rate_percent_nonnegative"),
            CheckConstraint("gross >= 0", name="ck_invoice_items_gross_nonnegative"),
            CheckConstraint("discount >= 0", name="ck_invoice_items_discount_nonnegative"),
            CheckConstraint("total >= 0", name="ck_invoice_items_total_nonnegative"),
            CheckConstraint("discount <= gross", name="ck_invoice_items_discount_not_above_gross"),
        ),
        "app_users": Table(
            "app_users",
            metadata,
            Column("id", BigInteger, primary_key=True, autoincrement=True),
            Column("username", String(120), nullable=False, unique=True),
            Column("password_hash", String(255), nullable=False),
            Column("role", String(20), nullable=False, server_default="admin"),
            Column("is_active", Boolean, nullable=False, server_default="true"),
            Column("created_at", DateTime(timezone=True), nullable=False),
            Column("updated_at", DateTime(timezone=True), nullable=False),
            CheckConstraint("char_length(btrim(username)) > 0", name="ck_app_users_username_not_blank"),
            CheckConstraint("char_length(btrim(password_hash)) > 0", name="ck_app_users_password_hash_not_blank"),
            CheckConstraint("role IN ('admin', 'operator')", name="ck_app_users_role_valid"),
        ),
    }
    return metadata, tables
