from __future__ import annotations

from collections.abc import Sequence

from .models import CatalogOffering, CatalogProduct
from ..types import CatalogOfferingData, CatalogProductData


def pack_price(unit_price: int, units: int) -> int:
    return unit_price * units


def kg_price(unit_price: int, kilos: int) -> int:
    return unit_price * kilos


DEFAULT_CATALOG: list[CatalogProductData] = [{'id': 'arvejas_partidas',
  'name': 'Arvejas Partidas',
  'aliases': ['Arvejas Partidas', 'Avejas Partidas'],
  'offerings': [{'id': '12x400', 'label': '12x400 gr', 'price': 9840, 'format_class': 'pack12'},
                {'id': '10x500', 'label': '10x500 gr', 'price': 9600, 'format_class': 'pack10_500'},
                {'id': 'x5kg', 'label': 'x 5 kg', 'price': 6300, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 39500, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 47400, 'format_class': 'bulk30'}]},
 {'id': 'avena_arrollada',
  'name': 'Avena Arrollada',
  'aliases': ['Avena Arrollada', 'Avena Arrrollada'],
  'offerings': [{'id': '16x300', 'label': '16x300 gr', 'price': 13120, 'format_class': 'pack12'},
                {'id': 'x4kg', 'label': 'x 4 kg', 'price': 8080, 'format_class': 'bag4'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 48250, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 57900, 'format_class': 'bulk30'}]},
 {'id': 'avena_instantanea',
  'name': 'Avena Instantánea',
  'aliases': ['Avena Instantánea', 'Avena Instantanea'],
  'offerings': [{'id': '12x350', 'label': '12x350 gr', 'price': 11640, 'format_class': 'pack12'},
                {'id': 'x4kg', 'label': 'x 4 kg', 'price': 9440, 'format_class': 'bag4'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 51250, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 61500, 'format_class': 'bulk30'}]},
 {'id': 'garbanzos',
  'name': 'Garbanzos',
  'aliases': ['Garbanzos'],
  'offerings': [{'id': '12x400', 'label': '12x400 gr', 'price': 10680, 'format_class': 'pack12'},
                {'id': '10x500', 'label': '10x500 gr', 'price': 11200, 'format_class': 'pack10_500'},
                {'id': 'x5kg', 'label': 'x 5 kg', 'price': 8950, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 43500, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 52200, 'format_class': 'bulk30'}]},
 {'id': 'harina_maiz_coccion_rapida',
  'name': 'Harina de Maíz Cocción Rápida',
  'aliases': ['Harina de Maíz Cocción Rápida', 'H. Maíz Cocc. Rápida', 'H. Maiz Cocc. Rapida'],
  'offerings': [{'id': '10x500', 'label': '10x500 gr', 'price': 5800, 'format_class': 'pack10_500'},
                {'id': 'x5kg', 'label': 'x 5 kg', 'price': 5200, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 25000, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 30000, 'format_class': 'bulk30'}]},
 {'id': 'harina_maiz',
  'name': 'Harina de Maíz',
  'aliases': ['Harina de Maíz', 'Harina de Maiz'],
  'offerings': [{'id': '12x400', 'label': '12x400 gr', 'price': 6720, 'format_class': 'pack12'},
                {'id': '10x500', 'label': '10x500 gr', 'price': 5600, 'format_class': 'pack10_500'},
                {'id': '10x1000', 'label': '10x1 kg', 'price': 10600, 'format_class': 'pack10_1000'},
                {'id': 'x5kg', 'label': 'x 5 kg', 'price': 5100, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 24500, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 29400, 'format_class': 'bulk30'}]},
 {'id': 'harina_maiz_blanca',
  'name': 'Harina de Maíz Blanca',
  'aliases': ['Harina de Maíz Blanca', 'Harina de Maiz Blanca'],
  'offerings': [{'id': '10x1000', 'label': '10x1 kg', 'price': 23400, 'format_class': 'pack10_1000'}]},
 {'id': 'lentejas',
  'name': 'Lentejas',
  'aliases': ['Lentejas', 'Lentjas'],
  'offerings': [{'id': '12x400', 'label': '12x400 gr', 'price': 16560, 'format_class': 'pack12'},
                {'id': '10x500', 'label': '10x500 gr', 'price': 16400, 'format_class': 'pack10_500'},
                {'id': 'x5kg', 'label': 'x 5 kg', 'price': 14750, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 69000, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 82800, 'format_class': 'bulk30'}]},
 {'id': 'maiz_pisingallo',
  'name': 'Maíz Pisingallo',
  'aliases': ['Maíz Pisingallo', 'Maiz Pisingallo'],
  'offerings': [{'id': '12x400', 'label': '12x400 gr', 'price': 8040, 'format_class': 'pack12'},
                {'id': '10x500', 'label': '10x500 gr', 'price': 8200, 'format_class': 'pack10_500'},
                {'id': 'x5kg', 'label': 'x 5 kg', 'price': 7350, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 35000, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 42000, 'format_class': 'bulk30'}]},
 {'id': 'maiz_pisado_blanco',
  'name': 'Maíz Pisado Blanco',
  'aliases': ['Maíz Pisado Blanco', 'Maiz Pisado Blanco', 'Maíz Partido Blanco', 'Maiz Partido Blanco'],
  'offerings': [{'id': '12x400', 'label': '12x400 gr', 'price': 11760, 'format_class': 'pack12'},
                {'id': '10x500', 'label': '10x500 gr', 'price': 12000, 'format_class': 'pack10_500'},
                {'id': 'x5kg', 'label': 'x 5 kg', 'price': 10500, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 51250, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 61500, 'format_class': 'bulk30'}]},
 {'id': 'porotos_alubia',
  'name': 'Porotos Alubia',
  'aliases': ['Porotos Alubia'],
  'offerings': [{'id': '12x400', 'label': '12x400 gr', 'price': 15840, 'format_class': 'pack12'},
                {'id': '10x500', 'label': '10x500 gr', 'price': 15800, 'format_class': 'pack10_500'},
                {'id': 'x5kg', 'label': 'x 5 kg', 'price': 13800, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 62500, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 75000, 'format_class': 'bulk30'}]},
 {'id': 'maiz_partido_colorado',
  'name': 'Maíz Partido Colorado',
  'aliases': ['Maíz Partido Colorado', 'Maiz Partido Colorado'],
  'offerings': [{'id': '10x500', 'label': '10x500 gr', 'price': 6700, 'format_class': 'pack10_500'},
                {'id': 'x5kg', 'label': 'x 5 kg', 'price': 6300, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 30000, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 36000, 'format_class': 'bulk30'}]},
 {'id': 'porotos_negros',
  'name': 'Porotos Negros',
  'aliases': ['Porotos Negros'],
  'offerings': [{'id': '10x500', 'label': '10x500 gr', 'price': 10400, 'format_class': 'pack10_500'},
                {'id': 'x5kg', 'label': 'x 5 kg', 'price': 11000, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 51250, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 61500, 'format_class': 'bulk30'}]},
 {'id': 'porotos_colorados',
  'name': 'Porotos Colorados',
  'aliases': ['Porotos Colorados'],
  'offerings': [{'id': '10x500', 'label': '10x500 gr', 'price': 15000, 'format_class': 'pack10_500'},
                {'id': 'x5kg', 'label': 'x 5 kg', 'price': 15500, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 72500, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 87000, 'format_class': 'bulk30'}]},
 {'id': 'porotos_soja',
  'name': 'Porotos Soja',
  'aliases': ['Porotos Soja'],
  'offerings': [{'id': '10x500', 'label': '10x500 gr', 'price': 5000, 'format_class': 'pack10_500'},
                {'id': 'x5kg', 'label': 'x 5 kg', 'price': 4750, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 21250, 'format_class': 'bulk25'}]},
 {'id': 'semola_trigo',
  'name': 'Sémola de Trigo',
  'aliases': ['Sémola de Trigo', 'Semola de Trigo', 'Sémola de trigo'],
  'offerings': [{'id': '12x400', 'label': '12x400 gr', 'price': 9240, 'format_class': 'pack12'},
                {'id': '10x500', 'label': '10x500 gr', 'price': 9000, 'format_class': 'pack10_500'},
                {'id': 'x5kg', 'label': 'x 5 kg', 'price': 8450, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 38500, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 46200, 'format_class': 'bulk30'}]},
 {'id': 'trigo_burgol',
  'name': 'Trigo Machacado Burgol',
  'aliases': ['Trigo Machacado Burgol', 'Trigo Burgol', 'Trigo Machacado Bulgol'],
  'offerings': [{'id': '12x400', 'label': '12x400 gr', 'price': 14400, 'format_class': 'pack12'},
                {'id': '10x500', 'label': '10x500 gr', 'price': 14200, 'format_class': 'pack10_500'},
                {'id': 'x5kg', 'label': 'x 5 kg', 'price': 12000, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 59500, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 71400, 'format_class': 'bulk30'}]},
 {'id': 'trigo_pelado',
  'name': 'Trigo Pelado',
  'aliases': ['Trigo Pelado'],
  'offerings': [{'id': '12x400', 'label': '12x400 gr', 'price': 8280, 'format_class': 'pack12'},
                {'id': '10x500', 'label': '10x500 gr', 'price': 8200, 'format_class': 'pack10_500'},
                {'id': 'x5kg', 'label': 'x 5 kg', 'price': 7500, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 34500, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 41400, 'format_class': 'bulk30'}]},
 {'id': 'mijo',
  'name': 'Mijo',
  'aliases': ['Mijo'],
  'offerings': [{'id': '10x500', 'label': '10x500 gr', 'price': 4800, 'format_class': 'pack10_500'}]},
 {'id': 'alpiste',
  'name': 'Alpiste',
  'aliases': ['Alpiste'],
  'offerings': [{'id': '10x500', 'label': '10x500 gr', 'price': 12800, 'format_class': 'pack10_500'}]},
 {'id': 'mezcla_pajaros',
  'name': 'Mezcla para Pájaros',
  'aliases': ['Mezcla para Pájaros', 'Mezcla para Pajaros'],
  'offerings': [{'id': '10x500', 'label': '10x500 gr', 'price': 8900, 'format_class': 'pack10_500'}]},
 {'id': 'arvejas_enteras',
  'name': 'Arvejas Enteras',
  'aliases': ['Arvejas Enteras'],
  'offerings': [{'id': 'x5kg', 'label': 'x 5 kg', 'price': 5750, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 36500, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 43800, 'format_class': 'bulk30'}]},
 {'id': 'arroz_parbolizado',
  'name': 'Arroz Parbolizado',
  'aliases': ['Arroz Parbolizado'],
  'offerings': [{'id': 'x5kg', 'label': 'x 5 kg', 'price': 7000, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 59250, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 71100, 'format_class': 'bulk30'}]},
 {'id': 'arroz_largo_fino',
  'name': 'Arroz Largo Fino 5/0',
  'aliases': ['Arroz Largo Fino 5/0', 'Arroz Largo Fino'],
  'offerings': [{'id': 'x5kg', 'label': 'x 5 kg', 'price': 6500, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 31500, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 37800, 'format_class': 'bulk30'}]},
 {'id': 'arroz_integral',
  'name': 'Arroz Integral Largo Fino',
  'aliases': ['Arroz Integral Largo Fino'],
  'offerings': [{'id': 'x5kg', 'label': 'x 5 kg', 'price': 7250, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 35000, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 42000, 'format_class': 'bulk30'}]},
 {'id': 'arroz_yamani',
  'name': 'Arroz Yamaní',
  'aliases': ['Arroz Yamaní', 'Arroz Yamani'],
  'offerings': [{'id': 'x5kg', 'label': 'x 5 kg', 'price': 12000, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 55000, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 66000, 'format_class': 'bulk30'}]},
 {'id': 'harina_maiz_abati',
  'name': 'Harina de Maíz Abatí',
  'aliases': ['Harina de Maíz Abatí', 'Harina de Maiz Abati'],
  'offerings': [{'id': 'x5kg', 'label': 'x 5 kg', 'price': 5100, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 25000, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 30000, 'format_class': 'bulk30'}]},
 {'id': 'harina_garbanzos',
  'name': 'Harina de Garbanzos',
  'aliases': ['Harina de Garbanzos'],
  'offerings': [{'id': 'x5kg', 'label': 'x 5 kg', 'price': 9000, 'format_class': 'bag5'},
                {'id': 'x25kg', 'label': 'x 25 kg', 'price': 38500, 'format_class': 'bulk25'},
                {'id': 'x30kg', 'label': 'x 30 kg', 'price': 46200, 'format_class': 'bulk30'}]}]


def catalog_for_api(catalog: Sequence[CatalogProduct | CatalogProductData] | None = None) -> list[CatalogProductData]:
    if catalog is None:
        return DEFAULT_CATALOG
    return [item.to_data() if isinstance(item, CatalogProduct) else item for item in catalog]


def catalog_indexes(catalog: Sequence[CatalogProduct | CatalogProductData] | None = None) -> tuple[dict[str, CatalogProductData], dict[tuple[str, str], CatalogOfferingData], dict[str, str]]:
    source = catalog_for_api(catalog)
    products_by_id: dict[str, CatalogProductData] = {}
    offerings_by_key: dict[tuple[str, str], CatalogOfferingData] = {}
    alias_to_product_id: dict[str, str] = {}

    for product in source:
        product_id = str(product['id'])
        products_by_id[product_id] = product
        for alias in product['aliases'] + [product['name']]:
            alias_to_product_id[alias.lower()] = product_id
        for offering in product['offerings']:
            offerings_by_key[(product_id, str(offering['id']))] = offering
    return products_by_id, offerings_by_key, alias_to_product_id
