"""Add application users table.

Revision ID: 6a4c2b9a7f11
Revises: e9330a12593a
Create Date: 2026-04-19 20:05:00.000000
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op


revision: str = "6a4c2b9a7f11"
down_revision: Union[str, Sequence[str], None] = "e9330a12593a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS app_users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(120) NOT NULL UNIQUE,
            password_hash VARCHAR(255) NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS app_users")
