"""Create and normalize current PostgreSQL schema.

Revision ID: e9330a12593a
Revises:
Create Date: 2026-04-16 23:23:24.043532
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "e9330a12593a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def table_exists(inspector: sa.Inspector, table_name: str) -> bool:
    return table_name in inspector.get_table_names(schema="public")


def column_exists(inspector: sa.Inspector, table_name: str, column_name: str) -> bool:
    if not table_exists(inspector, table_name):
        return False
    return column_name in {column["name"] for column in inspector.get_columns(table_name, schema="public")}


def create_current_schema() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS catalogs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            active BOOLEAN NOT NULL DEFAULT FALSE,
            source VARCHAR(120) NOT NULL,
            catalog JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS price_lists (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            filename VARCHAR(255) NOT NULL,
            content_type VARCHAR(120) NOT NULL,
            size INTEGER NOT NULL,
            pdf_data BYTEA NOT NULL,
            active BOOLEAN NOT NULL DEFAULT FALSE,
            source VARCHAR(120) NOT NULL,
            uploaded_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS transports (
            transport_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(255) NOT NULL UNIQUE,
            notes JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS customers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            secondary_line TEXT NOT NULL DEFAULT '',
            notes JSONB NOT NULL,
            footer_discounts JSONB NOT NULL,
            line_discounts_by_format JSONB NOT NULL,
            source_count INTEGER NOT NULL DEFAULT 0,
            transport_id BIGINT REFERENCES transports(transport_id) ON DELETE SET NULL,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS products (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            aliases JSONB NOT NULL,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS product_offerings (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
            label VARCHAR(120) NOT NULL,
            price INTEGER NOT NULL,
            position INTEGER NOT NULL,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL,
            UNIQUE(product_id, label)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS invoices (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
            transport_id BIGINT REFERENCES transports(transport_id) ON DELETE SET NULL,
            legacy_key VARCHAR(255) UNIQUE,
            client_name VARCHAR(255) NOT NULL,
            order_date DATE NOT NULL,
            secondary_line TEXT NOT NULL DEFAULT '',
            transport TEXT NOT NULL DEFAULT '',
            notes JSONB NOT NULL,
            footer_discounts JSONB NOT NULL,
            line_discounts_by_format JSONB NOT NULL,
            total_bultos INTEGER NOT NULL,
            gross_total INTEGER NOT NULL,
            discount_total INTEGER NOT NULL,
            final_total INTEGER NOT NULL,
            output_filename VARCHAR(255) NOT NULL,
            xlsx_data BYTEA NOT NULL,
            xlsx_size INTEGER NOT NULL,
            created_at TIMESTAMPTZ NOT NULL
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS invoice_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            invoice_id BIGINT NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
            line_number INTEGER NOT NULL,
            product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
            offering_id BIGINT REFERENCES product_offerings(id) ON DELETE SET NULL,
            label TEXT NOT NULL,
            quantity INTEGER NOT NULL,
            unit_price INTEGER NOT NULL,
            gross INTEGER NOT NULL,
            discount INTEGER NOT NULL,
            total INTEGER NOT NULL
        )
        """
    )


def migrate_legacy_schema(inspector: sa.Inspector) -> None:
    if not table_exists(inspector, "customers"):
        return
    if column_exists(inspector, "customers", "id"):
        return

    op.execute("DROP TABLE IF EXISTS invoice_items_new")
    op.execute("DROP TABLE IF EXISTS invoices_new")
    op.execute("DROP TABLE IF EXISTS product_offerings_new")
    op.execute("DROP TABLE IF EXISTS products_new")
    op.execute("DROP TABLE IF EXISTS customers_new")

    op.execute(
        """
        CREATE TABLE customers_new (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            customer_key VARCHAR(255) NOT NULL UNIQUE,
            name VARCHAR(255) NOT NULL,
            secondary_line TEXT NOT NULL DEFAULT '',
            notes JSONB NOT NULL,
            footer_discounts JSONB NOT NULL,
            line_discounts_by_format JSONB NOT NULL,
            source_count INTEGER NOT NULL DEFAULT 0,
            transport_id BIGINT REFERENCES transports(transport_id) ON DELETE SET NULL,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )
        """
    )
    op.execute(
        """
        INSERT INTO customers_new (
            customer_key, name, secondary_line, notes,
            footer_discounts, line_discounts_by_format,
            source_count, transport_id, created_at, updated_at
        )
        SELECT
            customer_key, name, secondary_line, notes,
            footer_discounts, line_discounts_by_format,
            source_count, transport_id, created_at, updated_at
        FROM customers
        ORDER BY created_at, customer_key
        """
    )

    op.execute(
        """
        CREATE TABLE products_new (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(255) NOT NULL,
            aliases JSONB NOT NULL,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL
        )
        """
    )
    op.execute(
        """
        INSERT INTO products_new (name, aliases, active, created_at, updated_at)
        SELECT name, aliases, active, created_at, updated_at
        FROM products
        ORDER BY created_at, product_id
        """
    )

    op.execute(
        """
        CREATE TABLE product_offerings_new (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            product_id BIGINT NOT NULL REFERENCES products_new(id) ON DELETE CASCADE,
            label VARCHAR(120) NOT NULL,
            price INTEGER NOT NULL,
            position INTEGER NOT NULL,
            active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL,
            updated_at TIMESTAMPTZ NOT NULL,
            UNIQUE(product_id, label)
        )
        """
    )
    op.execute(
        """
        INSERT INTO product_offerings_new (
            product_id, label, price, position, active, created_at, updated_at
        )
        SELECT
            products_new.id,
            product_offerings.label,
            product_offerings.price,
            product_offerings.position,
            product_offerings.active,
            product_offerings.created_at,
            product_offerings.updated_at
        FROM product_offerings
        JOIN products_new ON products_new.name = product_offerings.product_id
        ORDER BY product_offerings.created_at, product_offerings.offering_key
        """
    )

    op.execute(
        """
        CREATE TABLE invoices_new (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            customer_id BIGINT REFERENCES customers_new(id) ON DELETE SET NULL,
            transport_id BIGINT REFERENCES transports(transport_id) ON DELETE SET NULL,
            legacy_key VARCHAR(255) UNIQUE,
            client_name VARCHAR(255) NOT NULL,
            order_date DATE NOT NULL,
            secondary_line TEXT NOT NULL DEFAULT '',
            transport TEXT NOT NULL DEFAULT '',
            notes JSONB NOT NULL,
            footer_discounts JSONB NOT NULL,
            line_discounts_by_format JSONB NOT NULL,
            total_bultos INTEGER NOT NULL,
            gross_total INTEGER NOT NULL,
            discount_total INTEGER NOT NULL,
            final_total INTEGER NOT NULL,
            output_filename VARCHAR(255) NOT NULL,
            xlsx_data BYTEA NOT NULL,
            xlsx_size INTEGER NOT NULL,
            created_at TIMESTAMPTZ NOT NULL
        )
        """
    )
    op.execute(
        """
        INSERT INTO invoices_new (
            customer_id, transport_id, legacy_key, client_name,
            order_date, secondary_line, transport, notes,
            footer_discounts, line_discounts_by_format, total_bultos,
            gross_total, discount_total, final_total, output_filename,
            xlsx_data, xlsx_size, created_at
        )
        SELECT
            customers_new.id,
            invoices.transport_id,
            invoices.invoice_id,
            invoices.client_name,
            invoices.order_date,
            invoices.secondary_line,
            invoices.transport,
            invoices.notes,
            invoices.footer_discounts,
            invoices.line_discounts_by_format,
            invoices.total_bultos,
            invoices.gross_total,
            invoices.discount_total,
            invoices.final_total,
            invoices.output_filename,
            invoices.xlsx_data,
            invoices.xlsx_size,
            invoices.created_at
        FROM invoices
        LEFT JOIN customers_new ON customers_new.customer_key = invoices.customer_key
        ORDER BY invoices.created_at, invoices.invoice_id
        """
    )

    op.execute(
        """
        CREATE TABLE invoice_items_new (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            invoice_id BIGINT NOT NULL REFERENCES invoices_new(id) ON DELETE CASCADE,
            line_number INTEGER NOT NULL,
            product_id BIGINT REFERENCES products_new(id) ON DELETE SET NULL,
            offering_id BIGINT REFERENCES product_offerings_new(id) ON DELETE SET NULL,
            label TEXT NOT NULL,
            quantity INTEGER NOT NULL,
            unit_price INTEGER NOT NULL,
            gross INTEGER NOT NULL,
            discount INTEGER NOT NULL,
            total INTEGER NOT NULL
        )
        """
    )
    op.execute(
        """
        INSERT INTO invoice_items_new (
            id, invoice_id, line_number, product_id, offering_id,
            label, quantity, unit_price, gross, discount, total
        )
        SELECT
            invoice_items.id,
            invoices_new.id,
            invoice_items.line_number,
            products_new.id,
            product_offerings_new.id,
            invoice_items.label,
            invoice_items.quantity,
            invoice_items.unit_price,
            invoice_items.gross,
            invoice_items.discount,
            invoice_items.total
        FROM invoice_items
        JOIN invoices_new ON invoices_new.legacy_key = invoice_items.invoice_id
        LEFT JOIN products_new ON products_new.name = invoice_items.product_id
        LEFT JOIN product_offerings_new
            ON product_offerings_new.product_id = products_new.id
           AND product_offerings_new.label = invoice_items.label
        ORDER BY invoice_items.id
        """
    )
    op.execute("SELECT setval(pg_get_serial_sequence('invoice_items_new', 'id'), COALESCE((SELECT MAX(id) FROM invoice_items_new), 1), true)")

    op.execute("DROP TABLE invoice_items")
    op.execute("DROP TABLE invoices")
    op.execute("DROP TABLE product_offerings")
    op.execute("DROP TABLE products")
    op.execute("DROP TABLE customers")
    op.execute("ALTER TABLE customers_new RENAME TO customers")
    op.execute("ALTER TABLE products_new RENAME TO products")
    op.execute("ALTER TABLE product_offerings_new RENAME TO product_offerings")
    op.execute("ALTER TABLE invoices_new RENAME TO invoices")
    op.execute("ALTER TABLE invoice_items_new RENAME TO invoice_items")


def normalize_existing_schema(inspector: sa.Inspector) -> None:
    bind = op.get_bind()

    if table_exists(inspector, "discount_policies"):
        op.execute("DROP TABLE discount_policies")
    if table_exists(inspector, "client_profiles"):
        op.execute("DROP TABLE client_profiles")

    for table_name, column_name in [
        ("customers", "customer_key"),
        ("customers", "discount_policy_id"),
        ("customers", "mode"),
        ("customers", "line_discount_label"),
        ("customers", "transport"),
        ("products", "code"),
        ("product_offerings", "code"),
        ("product_offerings", "format_class"),
        ("invoices", "discount_policy_id"),
        ("invoices", "mode"),
    ]:
        if column_exists(inspector, table_name, column_name):
            op.execute(f'ALTER TABLE {table_name} DROP COLUMN IF EXISTS {column_name}')

    if table_exists(inspector, "invoices") and not column_exists(inspector, "invoices", "transport_id"):
        op.execute("ALTER TABLE invoices ADD COLUMN transport_id BIGINT")

    if table_exists(inspector, "customers") and column_exists(inspector, "customers", "transport"):
        rows = bind.execute(sa.text("SELECT id, transport, transport_id FROM customers ORDER BY id")).mappings().all()
        for row in rows:
            if row.get("transport_id") or not str(row.get("transport") or "").strip():
                continue
            transport_name = str(row["transport"]).strip()
            bind.execute(
                sa.text(
                    """
                    INSERT INTO transports (name, notes, created_at, updated_at)
                    VALUES (:name, '[]'::jsonb, now(), now())
                    ON CONFLICT (name) DO UPDATE SET updated_at = excluded.updated_at
                    """
                ),
                {"name": transport_name},
            )
            transport_id = bind.execute(
                sa.text("SELECT transport_id FROM transports WHERE name = :name"),
                {"name": transport_name},
            ).scalar_one()
            bind.execute(
                sa.text("UPDATE customers SET transport_id = :transport_id, updated_at = now() WHERE id = :id"),
                {"transport_id": transport_id, "id": row["id"]},
            )

    if table_exists(inspector, "invoices") and column_exists(inspector, "invoices", "transport"):
        rows = bind.execute(sa.text("SELECT id, transport, transport_id FROM invoices ORDER BY id")).mappings().all()
        for row in rows:
            if row.get("transport_id") or not str(row.get("transport") or "").strip():
                continue
            transport_name = str(row["transport"]).strip()
            bind.execute(
                sa.text(
                    """
                    INSERT INTO transports (name, notes, created_at, updated_at)
                    VALUES (:name, '[]'::jsonb, now(), now())
                    ON CONFLICT (name) DO UPDATE SET updated_at = excluded.updated_at
                    """
                ),
                {"name": transport_name},
            )
            transport_id = bind.execute(
                sa.text("SELECT transport_id FROM transports WHERE name = :name"),
                {"name": transport_name},
            ).scalar_one()
            bind.execute(
                sa.text("UPDATE invoices SET transport_id = :transport_id WHERE id = :id"),
                {"transport_id": transport_id, "id": row["id"]},
            )

    if table_exists(inspector, "catalogs"):
        catalog_rows = bind.execute(sa.text("SELECT id, catalog FROM catalogs ORDER BY id")).mappings().all()
        product_rows = bind.execute(sa.text("SELECT id, name FROM products")).mappings().all() if table_exists(inspector, "products") else []
        offering_rows = bind.execute(sa.text("SELECT id, product_id, label FROM product_offerings")).mappings().all() if table_exists(inspector, "product_offerings") else []
        product_by_name = {row["name"]: row["id"] for row in product_rows}
        offering_by_key = {(row["product_id"], row["label"]): row["id"] for row in offering_rows}
        for row in catalog_rows:
            normalized_catalog = []
            for product in row["catalog"] or []:
                product_name = product.get("name", "")
                product_id = product_by_name.get(product_name, product.get("id"))
                normalized_product = {
                    "id": product_id,
                    "name": product_name,
                    "aliases": product.get("aliases", []),
                    "offerings": [],
                }
                for offering in product.get("offerings", []):
                    offering_label = offering.get("label", "")
                    offering_id = offering_by_key.get((product_id, offering_label), offering.get("id"))
                    normalized_product["offerings"].append(
                        {
                            "id": offering_id,
                            "label": offering_label,
                            "price": int(offering.get("price", 0)),
                        }
                    )
                normalized_catalog.append(normalized_product)
            bind.execute(
                sa.text("UPDATE catalogs SET catalog = :catalog WHERE id = :id"),
                {"catalog": normalized_catalog, "id": row["id"]},
            )


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    create_current_schema()
    inspector = sa.inspect(bind)
    migrate_legacy_schema(inspector)
    inspector = sa.inspect(bind)
    normalize_existing_schema(inspector)


def downgrade() -> None:
    pass
